apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-spring
  labels:
    app: kubernetes-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-spring
  template:
    metadata:
      labels:
        app: kubernetes-spring
    spec:
      containers:
        - name: kubernetes-spring
          image: djuybu/kubernates-spring:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: kubernates-spring
            items:
              - key: application.properties
                path: application.properties
